-- RaceDocV1 Dashboard Summary RPC
-- Superseded by docs/RaceDocV1_Supabase_Dashboard_Role_Summaries.sql.
--
-- This file is intentionally comment-only. Older documentation linked here,
-- but the prior SQL referenced retired entries/requests schema names. Use the
-- role-aware Dashboard RPC file above when applying Dashboard summary changes
-- in the Supabase SQL Editor.
